"""Build a local, dependency-free research catalogue from the three owned datasets."""
import csv, html, json
from pathlib import Path
p=Path(__file__).resolve().parent
rows=[]
for name in ['assistants.json','orchestration.json','infrastructure-visuals.json']:
    rows.extend(json.loads((p/name).read_text()))
assert len(rows)==100 and len({r['repo'].lower() for r in rows})==100
for r in rows:
    assert r['source_urls'] and all(u.startswith('https://') for u in r['source_urls'])
(p/'catalogue.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
with (p/'catalogue.csv').open('w',newline='') as f:
    fields=['name','repo','category','fit','license','evidence','summary','useful_for','limitation','source_urls']
    w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader()
    for r in rows:w.writerow({**r,'source_urls':' | '.join(r['source_urls'])})
css='''*{box-sizing:border-box}body{margin:0;background:#f6f6f2;color:#22251f;font:14px -apple-system,BlinkMacSystemFont,sans-serif}main{max-width:1320px;margin:auto;padding:55px 32px}h1{font-size:42px;letter-spacing:-1.7px;font-weight:550;margin:15px 0}h2{font-size:19px;font-weight:550}p{line-height:1.8;color:#53594f}.eyebrow{font-size:11px;letter-spacing:2px}nav{display:flex;gap:19px;flex-wrap:wrap;margin:26px 0 35px}a{color:#344e2c;text-underline-offset:3px}input,select{font:inherit;padding:12px;border:1px solid #b8bfb1;background:white;border-radius:5px;max-width:100%}.filters{display:flex;gap:12px;flex-wrap:wrap;position:sticky;top:0;background:#f6f6f2;padding:15px 0;z-index:1}input{flex:1;min-width:180px}.intro{max-width:850px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-top:18px}article{padding:23px;border:1px solid #ced2c7;background:#fff;border-radius:7px}article h2{margin:12px 0}article p{font-size:12px;margin:12px 0}article .meta{font-size:10px;color:#616957;line-height:1.6}.label{font-size:10px;letter-spacing:1px;text-transform:uppercase}.links{display:flex;gap:13px;flex-wrap:wrap;font-size:12px;margin-top:18px}details{font-size:11px;line-height:1.8;margin-top:15px;overflow-wrap:anywhere}summary{cursor:pointer}#count{font-size:12px;color:#53594f;margin:12px 0}.shortlist{padding:20px 25px;border:1px solid #bec9b5;border-radius:7px;margin:25px 0}.shortlist p{font-size:13px;margin:7px 0}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){main{padding:30px 18px}.grid{grid-template-columns:1fr}h1{font-size:34px}.filters{position:static}select{width:100%}}'''
head='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PaneForge research · 100 projects</title><style>'''+css+'''</style></head><body><main><div class="eyebrow">PANEFORGE / RESEARCH LIBRARY / 13 SEPTEMBER 2026</div><h1>Better work, fewer moving parts.</h1><p class="intro">100 distinct repositories across assistants, orchestration, memory, computer use, inference and interface design. This is a discovery catalogue, not 100 competing complete products or 100 features to build. Some projects are source-available or restricted, not open source. No third-party project was installed or run for this research.</p><nav><a href="../../../design/paneforge-directions/studio.html">New studio concept</a><a href="../taskdriver-paneforge-product-boundary.md">Taskdriver vs PaneForge</a><a href="feature-value-matrix.md">Build / test / defer / cut</a><a href="scaling-and-claim.md">Agent scaling & claim check</a><a href="catalogue.csv">Download CSV</a></nav><div class="shortlist"><h2>Start with the patterns that solve a real problem</h2><p><a href="assistant-dossiers.md">OpenHands, Goose, AIRI</a>: sessions, approval state and assistant interaction. <a href="visual-reuse-dossiers.md">Magentic-UI, Motion, React Bits</a>: explicit next actions and controlled motion, with licence and performance limits. <a href="scaling-and-claim.md">LangGraph, Graphiti, Temporal</a>: persistence, memory scoping and recovery. Source and test inspection is stronger than a README claim, but does not establish runtime reliability.</p></div><div class="filters"><input id="search" aria-label="Search catalogue" placeholder="Search projects, capabilities, limitations…"><select id="fit" aria-label="Recommendation"><option value="">Every recommendation</option><option>shortlist</option><option>consider</option><option>reference</option></select><select id="category" aria-label="Category"><option value="">Every category</option>'''
head+=''.join('<option>'+html.escape(c)+'</option>' for c in sorted({r['category'] for r in rows}))
head+='''</select></div><div id="count" role="status"></div><div class="grid" id="grid"></div><p>Fit is a planning judgement, not a benchmark ranking. Repository links and mutable documentation were checked during research; pin source revisions and recheck licences before adoption. The prototype’s task counts and conversations are fictional.</p></main><script>const records='''+json.dumps(rows,ensure_ascii=False).replace('<','\\u003c')+''';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function render(){const q=document.querySelector('#search').value.toLowerCase(),fit=document.querySelector('#fit').value,cat=document.querySelector('#category').value;const a=records.filter(r=>(!fit||r.fit===fit)&&(!cat||r.category===cat)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));document.querySelector('#count').textContent=a.length+' of 100 projects';document.querySelector('#grid').innerHTML=a.map(r=>`<article><div class="label">${esc(r.category)} · ${esc(r.fit)}</div><h2>${esc(r.name)}</h2><div class="meta">${esc(r.repo)}<br>Licence: ${esc(r.license)}</div><p>${esc(r.summary)}</p><p><strong>Useful for</strong><br>${esc(r.useful_for)}</p><p><strong>Limit</strong><br>${esc(r.limitation)}</p><div class="links"><a href="https://github.com/${esc(r.repo)}" target="_blank" rel="noopener">Repository ↗</a>${r.demo_url&&r.demo_url.startsWith('https://')?`<a href="${esc(r.demo_url)}" target="_blank" rel="noopener">Website / demo ↗</a>`:''}${r.image_url&&r.image_url.startsWith('https://')?`<a href="${esc(r.image_url)}" target="_blank" rel="noopener">Visual reference ↗</a>`:''}</div><details><summary>Evidence & sources</summary><p>${esc(r.evidence)}<br>Checked: ${esc(r.checked_at||'See dossier')}</p>${r.source_urls.map(u=>`<a href="${esc(u)}" target="_blank" rel="noopener">${esc(u)}</a><br>`).join('')}</details></article>`).join('')||'<p>No matching projects.</p>'}document.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',render));render();</script></body></html>'''
# The catalogue is at docs/research/open-source-harness-catalogue.
head=head.replace('../../../design/','../../design/')
(p/'index.html').write_text(head)
print('Built 100 unique research records, CSV and local viewer.')
