import { spawn, execFile as execFileCallback } from 'node:child_process';
import { promisify } from 'node:util';
import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
const execFile=promisify(execFileCallback), SESSION_ID=/^[0-9a-f]{8}-[0-9a-f-]{27}$/i;
const MCP_NAME='paneforge_fixture', READ_ONLY_TOOLS=['list_project_files','read_fixture','read_project_file','search_conversation_history','search_second_brain'];
const ALLOWED_TOOLS=READ_ONLY_TOOLS.map(name=>`mcp__${MCP_NAME}__${name}`);
const SYSTEM_PROMPT='You are a read-only PaneForge Chat conversation. Use only the supplied PaneForge read-only tools. Do not run commands, edit files, browse, use network tools, invoke plugins, hooks, skills, or project instructions. State when execution would require the real PC Codex CLI.';
function filteredEnv(){return Object.fromEntries(Object.entries(process.env).filter(([key])=>!/(API_KEY|ACCESS_TOKEN|AUTH_TOKEN|SECRET|ANTHROPIC_BASE_URL|CLAUDE_CODE_USE_(?:BEDROCK|VERTEX))/i.test(key)));}
function cancelled(){const error=Error('Claude conversation was cancelled.');error.code='CANCELLED';return error;}
function failure(message){const error=Error(`Claude Chat failed: ${String(message||'unknown provider failure').trim().slice(0,400)}`);error.code='PROVIDER_ERROR';return error;}
function config(projectId,cwd){if(typeof projectId!=='string'||!/^[A-Za-z0-9_-]{1,80}$/.test(projectId))throw Error('Claude project scope is invalid.');return JSON.stringify({mcpServers:{[MCP_NAME]:{command:process.execPath,args:[resolve('server/fixture-mcp.mjs')],env:{PANEFORGE_PROJECT_ID:projectId,PANEFORGE_PROJECT_CWD:cwd,PANEFORGE_DATA_DIR:resolve(process.env.PANEFORGE_DATA_DIR||'.local-runtime/app')}}}});}
function initError(event,sessionId){if(event?.type!=='system'||event.subtype!=='init')return null;if(event.session_id!==sessionId)return 'Claude returned a mismatched native session identity.';if(!Array.isArray(event.tools))return 'Claude did not report its effective tool set.';const toolNames=event.tools.map(tool=>String(tool).replace(`mcp__${MCP_NAME}__`,'')).sort();if(JSON.stringify(toolNames)!==JSON.stringify([...READ_ONLY_TOOLS].sort()))return 'Claude exposed tools outside the PaneForge MCP scope.';const servers=(event.mcp_servers||[]).map(x=>typeof x==='string'?x:x?.name);return servers.length===1&&servers[0]===MCP_NAME?false:'Claude did not expose exactly the PaneForge read-only MCP server.';}
export class Claude {
 constructor({command=process.env.PANEFORGE_CLAUDE||'claude',spawnFn=spawn,execFileFn=execFile}={}){this.command=command;this.spawnFn=spawnFn;this.execFile=execFileFn;this.running=new Map();}
 async start(){let stdout;try{({stdout}=await this.execFile(this.command,['auth','status'],{env:filteredEnv(),timeout:15000,maxBuffer:32000}));}catch(error){throw Error(`Claude authentication check failed: ${String(error.stderr||error.message||error).slice(0,180)}`);}let account;try{account=JSON.parse(stdout);}catch{throw Error('Claude authentication check returned an invalid result.');}if(!account?.loggedIn||account.authMethod!=='claude.ai'||account.apiProvider!=='firstParty'||account.subscriptionType!=='max')throw Error('Claude.ai Max subscription authentication required. Paid API fallback is disabled.');return {status:'ready',authType:account.authMethod,plan:account.subscriptionType,model:'claude',tools:READ_ONLY_TOOLS};}
 create(){return randomUUID();}
 async resume(sessionId){if(!SESSION_ID.test(sessionId||''))throw Error('Claude native session identity is invalid.');return {nativeSessionId:sessionId};}
 async send({sessionId,projectId,cwd,text,resume=true,onEvent=()=>{}}){if(!SESSION_ID.test(sessionId||''))throw Error('Claude native session identity is invalid.');if(typeof cwd!=='string'||!cwd||cwd.length>1000||typeof text!=='string'||!text.trim())throw Error('Claude conversation input is invalid.');if(this.running.has(sessionId))throw Error('Claude conversation is already running.');const args=['--print','--output-format','stream-json','--verbose','--include-partial-messages','--restricted','--strict-mcp-config','--mcp-config',config(projectId,cwd),'--tools','','--allowedTools',...ALLOWED_TOOLS,'--permission-mode','plan','--permission-prompts','none','--disable-slash-commands','--no-chrome','--prompt-suggestions','false','--system-prompt',SYSTEM_PROMPT,...(resume?['--resume',sessionId]:['--session-id',sessionId]),text];return await new Promise((resolveResult,reject)=>{let child;try{child=this.spawnFn(this.command,args,{cwd,env:filteredEnv(),stdio:['ignore','pipe','pipe']});}catch(error){reject(error);return;}this.running.set(sessionId,child);let stderr='',output='',providerError='',sawInit=false,sawResult=false,settled=false,pending='';const finish=(error,result)=>{if(settled)return;settled=true;this.running.delete(sessionId);error?reject(error):resolveResult(result);};const handle=event=>{const bad=initError(event,sessionId);if(bad){providerError=bad;return;}if(event?.type==='system'&&event.subtype==='init')sawInit=true;const delta=event?.type==='stream_event'&&event.event?.type==='content_block_delta'?event.event.delta?.text:null;if(typeof delta==='string'&&delta){output=(output+delta).slice(0,24000);onEvent({type:'delta',text:delta.slice(0,24000)});}const source=event.event||event;if(source?.type==='content_block_start'&&source.content_block?.type==='tool_use')onEvent({type:'tool',id:source.content_block.id,name:source.content_block.name,status:'started'});if(source?.type==='content_block_stop')onEvent({type:'tool',status:'completed'});if(event?.type==='result'){sawResult=true;if(event.is_error)providerError=event.result;else if(!output){output=event.result.slice(0,24000);onEvent({type:'message',text:output});}}};child.stdout.on('data',chunk=>{pending=(pending+chunk.toString()).slice(-64000);for(;;){const end=pending.indexOf('\n');if(end<0)break;const line=pending.slice(0,end);pending=pending.slice(end+1);try{handle(JSON.parse(line));}catch{}}});child.stderr.on('data',chunk=>{if(stderr.length<600)stderr=(stderr+chunk.toString()).slice(0,600);});child.on('error',error=>finish(error));child.on('close',code=>{if(this.running.get(sessionId)===child&&child.killed)return finish(cancelled());if(providerError)return finish(failure(providerError));if(!sawInit)return finish(failure('Claude did not provide a verified session initialization event.'));if(!sawResult)return finish(failure('Claude exited without a final result receipt.'));if(code!==0)return finish(failure(stderr||`exit ${code}`));finish(null,{nativeSessionId:sessionId,text:output});});});}
 async stop(sessionId){const child=this.running.get(sessionId);if(!child)return false;child.kill('SIGINT');return true;}
 close(){for(const [sessionId,child] of this.running){try{child.kill('SIGINT');setTimeout(()=>{if(this.running.get(sessionId)===child)child.kill('SIGKILL');},1500).unref?.();}catch{}}}
}
export const claudeReadOnlyTools=READ_ONLY_TOOLS;
