// What the Stash is not allowed to remember.
//
// A password copied out of 1Password used to land in `history.json` as plaintext and sit
// there for 200 items. Every clipboard manager worth the name has an answer to this and
// ours threw the answer away: the marker is already in `clipboard.availableFormats()`,
// which `recents.ts` reads on every tick and then only looked at for `image/`.
//
// Two independent nets, because they catch different things:
//
//   1. The MARKER, always on and not configurable. The copying app said "do not remember
//      this". macOS has had `org.nspasteboard.ConcealedType` as a convention for years
//      (1Password, Bitwarden, KeePassXC, Maccy, Alfred all honour it); Windows has two
//      registered clipboard formats that mean the same thing to Win+V. Neither is a
//      guess about the content - it is the source app telling us, and the only correct
//      response is to store nothing at all, not to store it and hide it.
//
//   2. A DENY LIST of patterns the user types in Settings > Stash, off by default. This
//      is the net for the app that sets no marker. It is deliberately not a built-in list
//      of secret shapes: copying an API key to paste it AT an agent is a thing people do
//      here all day, and an app that silently swallowed it would read as broken.
//
// Both are decided BEFORE anything is written, so an excluded clip never reaches the disk
// even for the moment before it is trimmed off the end.

/**
 * Clipboard format names that mean "do not remember this".
 *
 * macOS side is the `org.nspasteboard.*` convention (nspasteboard.org). `ConcealedType`
 * is a password; `TransientType` and `AutoGeneratedType` are "this was not typed by a
 * person and is not worth a history slot", which is the same answer for us.
 *
 * Windows side: `ExcludeClipboardContentFromMonitorProcessing` is the strong one - its
 * documented meaning is that no other process should even look. `CanIncludeInClipboardHistory`
 * and `CanUploadToCloudClipboard` carry a DWORD, 0 meaning no, and Electron's
 * `availableFormats()` hands us names without their data. Presence is treated as a no,
 * because the only reason to register either format is to say no: allowing is the default
 * and needs no format at all. The cost of being wrong that way is one clip not stashed;
 * the cost of the other way is a password on disk.
 */
export const CONCEALED_FORMATS = [
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  'ExcludeClipboardContentFromMonitorProcessing',
  'CanIncludeInClipboardHistory',
  'CanUploadToCloudClipboard'
] as const

/**
 * Which marker said no, or null if none did.
 *
 * The name is returned rather than a boolean so the one line the log gets can say which
 * app convention fired - "concealed (org.nspasteboard.ConcealedType)" is diagnosable and
 * "concealed" is not, and this is a path nobody can see the output of by definition.
 *
 * Matching is case-insensitive and ignores a `public.` / `dyn.` wrapper: macOS reports a
 * type registered by an app that never declared a UTI as an opaque `dyn.a...` string with
 * the real name inside it.
 */
export function concealedBy(formats: readonly string[]): string | null {
  for (const raw of formats) {
    const f = String(raw).toLowerCase()
    for (const marker of CONCEALED_FORMATS) {
      const m = marker.toLowerCase()
      if (f === m || f.endsWith(`.${m}`) || f.includes(m)) return marker
    }
  }
  return null
}

/**
 * One line of the user's deny list, compiled.
 *
 * `/re/flags` is a regular expression, anything else is a case-insensitive substring -
 * because "the word staging" is what somebody actually wants to type, and making them
 * escape it first is how a privacy setting ends up switched off. A line that will not
 * compile is dropped rather than thrown: this list is read on a clipboard tick and one
 * bad character may not stop the other rules working.
 */
export function compileDeny(list: string): RegExp[] {
  const out: RegExp[] = []
  for (const line of String(list || '').split(/\r?\n/)) {
    const s = line.trim()
    if (!s || s.startsWith('#')) continue
    const re = /^\/(.+)\/([gimsuy]*)$/.exec(s)
    try {
      out.push(re ? new RegExp(re[1], re[2].replace('g', '')) : new RegExp(escapeRe(s), 'i'))
    } catch {
      /* an unparseable line is one dead rule, never a dead list */
    }
  }
  return out
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

/** Does the user's deny list refuse this text? Returns the rule that matched, for the log. */
export function deniedBy(text: string, rules: readonly RegExp[]): string | null {
  for (const r of rules) {
    // A global flag would carry lastIndex between clips and make the same rule match
    // every other time. compileDeny strips `g`; this is the belt for a rule built elsewhere.
    r.lastIndex = 0
    if (r.test(text)) return r.source
  }
  return null
}
