// GENERATED by scripts/settings-index.mjs - run `npm run gen:settings` after adding a
// setting. `npm run test:settingsearch` fails when this disagrees with the dialog's source.
//
// One entry per setting the Settings dialog draws: which tab it is on, the words on it,
// and the words it can be found by (its label plus the sentence under it).

export interface SettingEntry {
  tab: string
  label: string
  find: string
}

export const SETTINGS: SettingEntry[] = [
  { tab: 'general', label: "Projects folder", find: "Projects folder" },
  { tab: 'general', label: "Default agent", find: "Default agent" },
  { tab: 'general', label: "Terminal font size", find: "Terminal font size" },
  { tab: 'general', label: "Selecting text in a pane copies it", find: "Selecting text in a pane copies it Ctrl+C copies while something is highlighted and interrupts the agent once nothing is. Ctrl+V pastes." },
  { tab: 'general', label: "A drag always selects text", find: "A drag always selects text Claude Code and Codex ask for the mouse, which leaves a drag selecting nothing. Turn this off to give them the drag back. The wheel scrolls this pane either way." },
  { tab: 'general', label: "Click moves the cursor", find: "Click moves the cursor A CLI’s prompt is drawn text, so a click cannot place a caret there - it is sent as the arrow keys that would have reached the same spot. A plain click works along the line you are typing, wrapped rows included, and sends left and right only. Option-click Alt-click reaches other lines too, and is held behind the modifier because in a plain shell an up-arrow recalls the last command instead of moving." },
  { tab: 'general', label: "Repair a pane's display after a resize", find: "Repair a pane's display after a resize Makes the agent repaint its whole frame once the size settles, so a resize cannot leave torn boxes behind. Ctrl+Shift+L does it on demand." },
  { tab: 'general', label: "Notify me when a background session goes quiet", find: "Notify me when a background session goes quiet Taskbar flash plus a system notification, only while the app is not focused." },
  { tab: 'general', label: "Chime when a session finishes its turn", find: "Chime when a session finishes its turn Plays even while PaneForge is focused - a pane you are not reading can still finish. Which sound it makes, and the sound for the other two alerts, is on the Sounds tab." },
  { tab: 'general', label: "Send a pane's question to Telegram", find: "Send a pane's question to Telegram A question stops the run until somebody presses a row, and the pane looks finished while it waits - so this one alert leaves the machine. Needs TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in the environment or in ~/.claude/usage-notify.env; without them nothing is sent. Message only: answering is still a press here or on the phone." },
  { tab: 'general', label: "Say something when a pane rings its bell", find: "Say something when a pane rings its bell A CLI that rings the terminal bell is asking for a person - a prompt it needs answered, a build that failed. The pane marks itself and plays its sound. Its own switch because a chatty CLI must be mutable without muting the turn chime." },
  { tab: 'general', label: "Warn me when a running turn goes silent", find: "Warn me when a running turn goes silent" },
  { tab: 'general', label: "Feature notes", find: "Feature notes" },
  { tab: 'general', label: "Stay out of the way while a game is running", find: "Stay out of the way while a game is running Windows takes a fullscreen game off the screen whenever a window appears above it, so while one of the games below is running PaneForge opens no windows, floats no Stash, flashes nothing and holds its update restart until you are done. The chime still plays." },
  { tab: 'general', label: "Do not disturb, right now", find: "Do not disturb, right now The same silence, on until you turn it off, whether or not a game is running." },
  { tab: 'general', label: "Give a second session in the same project its own lane", find: "Give a second session in the same project its own lane Two agents in one folder overwrite each other's edits, race git and fight over the dev server port. The second session in a repo opens in a lane instead - <project>-a on branch lane-a, then -b, then -c - carrying your .env files, your local settings, and the installed node_modules (hardlinked a few seconds after the pane opens, so it costs no disk and deleting the lane never touches the original). It also gets its own PORT (one past whatever the project's dev script uses, also in PF_LANE_PORT) and the original folder's Claude history, memory and permissions instead of a blank slate. Click the lane chip on the pane to see what is in it and merge it back when the work is done." },
  { tab: 'general', label: "Start a pane on a paired device when this machine is full", find: "Start a pane on a paired device when this machine is full Only once panes here already cost more memory than the machine has, and only for a project that device also has. The launch says where it went." },
  { tab: 'general', label: "Ask first, rather than moving it", find: "Ask first, rather than moving it Off, and off is the default: where a pane runs is answered by the budget below rather than by a dialog per launch. On puts the question back - it recommends the paired device, and remembers your answer for ten minutes so a burst of panes asks once." },
  { tab: 'general', label: "Move a finished pane to a paired device when this machine is full", find: "Move a finished pane to a paired device when this machine is full The setting above stops it getting worse by starting the NEXT pane over there; this moves one that is already open, with its conversation, its branch, its screen and the dev server it had running. It fires on the budget below, and on either sign of a machine in trouble - the kernel saying it is out of memory, or the load average saying this desk is lagging, whichever comes first (memory says so late: nine agents here once read as merely tight while the load ran at 8.7 on 10 cores). Only to a device that is online and has the same project. A pane mid-turn is never killed - it is queued and goes the moment its turn ends, because killing a pty mid-answer loses the answer. A pane holding a question on screen is never moved at all. If nothing can take it, the pane is closed instead, which keeps its conversation and its screen in History." },
  { tab: 'general', label: "Panes this machine runs itself", find: "Panes this machine runs itself" },
  { tab: 'general', label: "...and move a quiet one over there even when there is still room", find: "...and move a quiet one over there even when there is still room The setting above only fires once the machine says it is out of memory, and it refuses any pane that is on screen - which with the grid on is every pane, so on a one-window desk it can never fire at all. This is the clock instead: a pane nobody has typed into for minutes moves to the paired device whatever the memory says, because an idle agent costs its ~190 MB the whole time it sits there and the lag arrives long before the kernel admits to it. Every other refusal is unchanged - never the pane you are in, never one mid-turn, never one holding a question, never the last pane - and the pane comes straight back as a mirror, so you keep watching it and typing into it from here." },
  { tab: 'general', label: "Let the little one keep an eye on this machine", find: "Let the little one keep an eye on this machine Everything above happens silently - panes are trimmed, moved and closed by three timers whose only output is a line in a console nobody has open. This is the face on them: it walks to the pane it is talking about, says what was done in a bubble, and offers a press before anything is closed. It answers typed questions about this window too - 'what are the two biggest', 'close the idle ones', 'what is pane 3' - out of readings the app already holds, with no model and no request to anywhere. It never takes focus, never opens a dialog, and it is silent until you press the speaker on its bubble." },
  { tab: 'general', label: "...and let it wander over to the pane it means, and run about now and then", find: "...and let it wander over to the pane it means, and run about now and then Walking to the card is how it says WHICH pane without you reading an id, and every nine minutes or so it chases a ball along the bottom of the window - only ever while it has nothing to say, is where the app put it, and somebody is looking at this window. Off parks it in the bottom-left corner; the bubble and everything you can ask it are unchanged." },
  { tab: 'general', label: "Which pet", find: "Which pet" },
  { tab: 'general', label: "Take what it says away after", find: "Take what it says away after" },
  { tab: 'general', label: "Show the occasional tip about what this app can do", find: "Show the occasional tip about what this app can do A small card in the bottom-right corner, about once every forty minutes, naming one thing that is genuinely hard to find - deleting a highlighted prompt, driving this desk from a phone, handing a pane to another machine mid-turn. It costs nothing: every line is a fixed sentence, there is no model and no request. It stays quiet while a dialog is open, while an update card is up and while any pane is holding a question, and every few tips it carries its own off switch." },
  { tab: 'general', label: "Close a pane nobody has touched for a while", find: "Close a pane nobody has touched for a while Off, a pane is only ever closed when this machine is genuinely out of memory - which is why a desk with room keeps every pane open for ever, however quiet they are. On, a pane nobody has typed into for minutes is closed whatever the memory says, because an idle agent costs its ~190 MB the whole time it sits there. Nothing is lost: a closed pane keeps its conversation and what was on its screen, and reopening it from History puts both back. The refusals are the same either way - never the pane you are in, never one that is working or starting, never one holding a question, never another device's pane, and never the last one open." },
  { tab: 'general', label: "Answer an agent's question for me when the answer is obvious", find: "Answer an agent's question for me when the answer is obvious A CLI that asks 'may I do this?' stops until somebody presses return, and at the desk that press is usually a formality. This reads the options and presses the one that plainly means go on - a single 'Yes'-shaped answer and nothing else. It never picks an option that widens permission ('and don't ask again'), never picks one that stops or asks for a sentence back, and leaves anything with no obvious answer on screen as buttons. A question is only answered after it has sat still for a moment, so you can still reach it first, and only once - a press that does not take is left alone rather than repeated." },
  { tab: 'general', label: "...and take the CLI's own default for the rest", find: "...and take the CLI's own default for the rest A question with several real answers ('which of these three shapes?') is a decision you are being asked to make, so by default it waits for you. On, the app takes the row the CLI's own arrow is already on - its preference, not one invented here - and keeps the run moving. The two refusals above still hold." },
  { tab: 'general', label: "Wait before answering", find: "Wait before answering" },
  { tab: 'general', label: "Ask before closing a running session", find: "Ask before closing a running session Exited panes always close without a prompt." },
  { tab: 'general', label: "Start PaneForge when the computer starts", find: "Start PaneForge when the computer starts Re-applied on every launch, not only when this is switched. The Windows Run entry is exactly the kind of thing an installer or a cleanup tool removes, and its absence reads as 'it did not reopen after a restart' with this switch still showing On." },
  { tab: 'general', label: "Keep a PaneForge shortcut on the Desktop", find: "Keep a PaneForge shortcut on the Desktop A launch that finds the shortcut missing puts it back. Our own installer used to delete it on every update, and Windows' maintenance task removes desktop shortcuts it decides are broken - either way the app looks uninstalled. An existing shortcut is never rewritten." },
  { tab: 'general', label: "Keep a searchable transcript of every pane", find: "Keep a searchable transcript of every pane Stored on this machine only. Deleted after days." },
  { tab: 'general', label: "Games to watch for", find: "Games to watch for" },
  { tab: 'stash', label: "Stash", find: "Stash" },
  { tab: 'stash', label: "Keep what I copy on the Stash", find: "Keep what I copy on the Stash Anything you copy anywhere - text, or a screenshot - lands bottom-left and stays on a history that survives restarts. Click text to paste it into the focused pane, click an image to type the path of a saved PNG the agent can read, or drag it out to another app. Ctrl+Shift+V reopens it. Off stops the clipboard being watched at all." },
  { tab: 'stash', label: "Float the Stash over every other app", find: "Float the Stash over every other app A small pill in the bottom-left corner of whichever screen PaneForge is on, on top of every window, whether or not the app is focused. Hover it, or press Ctrl+Alt+V from anywhere, for the whole Stash: click a line to put it back on the clipboard, → to send it to the focused pane, ✕ to forget it. It never takes the keyboard, so you can click a line and paste straight back into what you were typing in. Files can be dropped straight onto the pill." },
  { tab: 'stash', label: "Only when I ask for it", find: "Only when I ask for it Nothing on screen until you press Ctrl+Alt+V, and then the Stash opens where your pointer already is and puts itself away again. Everything you copy is still captured either way - this is only about whether a pill sits over your other windows waiting to be hovered." },
  { tab: 'stash', label: "Show itself for", find: "Show itself for" },
  { tab: 'stash', label: "Keep", find: "Keep" },
  { tab: 'stash', label: "Screenshots kept", find: "Screenshots kept" },
  { tab: 'stash', label: "Files you drop on it", find: "Files you drop on it" },
  { tab: 'stash', label: "Biggest file accepted", find: "Biggest file accepted" },
  { tab: 'stash', label: "Never remember", find: "Never remember" },
  { tab: 'agents', label: "Agents on this machine", find: "Agents on this machine" },
  { tab: 'agents', label: "key", find: "key" },
  { tab: 'agents', label: "Default model per agent", find: "Default model per agent" },
  { tab: 'voice', label: "Dictation", find: "Dictation" },
  { tab: 'voice', label: "Transcriber", find: "Transcriber" },
  { tab: 'voice', label: "Model", find: "Model" },
  { tab: 'voice', label: "Language", find: "Language" },
  { tab: 'voice', label: "Show a mic on every pane, and enable the global push-to-talk key", find: "Show a mic on every pane, and enable the global push-to-talk key" },
  { tab: 'discord', label: "Show what the desk is doing on Discord", find: "Show what the desk is doing on Discord Rich presence on your profile, refreshed as turns start and finish. Counts and project folder names only, never a byte of what a pane says. Needs the Discord app running; off tells Discord nothing at all." },
  { tab: 'discord', label: "What Discord will show", find: "What Discord will show" },
  { tab: 'discord', label: "Name the projects being worked in", find: "Name the projects being worked in The second line. Folder names of the panes whose turn is running - off leaves only the numbers, which says you are busy without saying on what." },
  { tab: 'discord', label: "Show the elapsed clock", find: "Show the elapsed clock Discord counts up from the oldest running turn, or from when PaneForge started while everything is idle." },
  { tab: 'discord', label: "Keep showing something while nothing is running", find: "Keep showing something while nothing is running Off clears the presence the moment the last turn finishes, so your profile only says PaneForge while there is actually work happening." },
  { tab: 'discord', label: "First line, while a turn is running", find: "First line, while a turn is running" },
  { tab: 'discord', label: "Second line", find: "Second line" },
  { tab: 'discord', label: "First line, while nothing is running", find: "First line, while nothing is running" },
  { tab: 'discord', label: "Put a clickable link under it", find: "Put a clickable link under it Discord draws the two lines above as plain text, so a URL written into them is not a link. A button is the only clickable thing a rich presence has - and Discord shows it to everyone except you, so your own profile will not have it." },
  { tab: 'discord', label: "Button text", find: "Button text" },
  { tab: 'discord', label: "Where it goes", find: "Where it goes" },
  { tab: 'system', label: "Administrator", find: "Administrator" },
  { tab: 'system', label: "Always start as administrator, with no UAC prompt", find: "Always start as administrator, with no UAC prompt Registers a Windows scheduled task once (one approval, ever) and points your shortcuts at it. Every agent pane then inherits admin rights." },
  { tab: 'system', label: "Updates", find: "Updates" },
  { tab: 'system', label: "Check for updates in the background", find: "Check for updates in the background Downloads quietly, then asks before restarting." },
  { tab: 'system', label: "Dev channel: take every build the moment it is cut", find: "Dev channel: take every build the moment it is cut New releases start as dev builds and everyone else updates only when one is promoted. On, this install is the proving ground - newer, sooner, less proven." },
  { tab: 'system', label: "Reopen my panes after an update restart", find: "Reopen my panes after an update restart On, an update feels like the app blinked and every pane resumes its conversation. Off, a restart is a clean desk." },
  { tab: 'system', label: "…and ask first, like every other restart", find: "…and ask first, like every other restart Off, an update restart is the one restart that never asks - it was the app's own idea, so it hands the desk straight back. On, it offers the panes exactly as a quit or a crash does." },
  { tab: 'system', label: "After a restart or a crash", find: "After a restart or a crash" },
  { tab: 'system', label: "Transcript retention", find: "Transcript retention" },
  { tab: 'system', label: "Right now", find: "Right now" },
  { tab: 'appearance', label: "Theme", find: "Theme" },
  { tab: 'appearance', label: "Your colour", find: "Your colour" },
  { tab: 'appearance', label: "Colour in the greys", find: "Colour in the greys" },
  { tab: 'appearance', label: "How dark", find: "How dark" },
  { tab: 'appearance', label: "Corners", find: "Corners" },
  { tab: 'appearance', label: "Density", find: "Density" },
  { tab: 'appearance', label: "Preview", find: "Preview" },
  { tab: 'sounds', label: "Volume", find: "Volume" },
  { tab: 'sounds', label: "Your own sounds", find: "Your own sounds" }
]

/**
 * The settings a query hits, best first.
 *
 * Every word has to appear somewhere in the entry - AND, the same rule the tab rail uses -
 * so a second word narrows. A hit on the LABEL outranks one that only matched the
 * explaining sentence underneath: the label is what the person is looking at.
 */
export function findSettings(query: string): SettingEntry[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean)
  if (!words.length) return []
  const scored: { entry: SettingEntry; score: number }[] = []
  for (const entry of SETTINGS) {
    const label = entry.label.toLowerCase()
    const find = entry.find.toLowerCase()
    if (!words.every((w) => find.includes(w))) continue
    const inLabel = words.filter((w) => label.includes(w)).length
    scored.push({ entry, score: inLabel })
  }
  scored.sort((a, b) => b.score - a.score)
  return scored.map((s) => s.entry)
}
