// GENERATED by scripts/settings-index.mjs - run `npm run gen:settings` after adding a
// setting. `npm run test:settingsearch` fails when this disagrees with the dialog's source.
//
// One entry per setting the Settings dialog draws: which tab it is on, the words on it,
// and the words it can be found by (its label plus the sentence under it).

export interface SettingEntry {
  tab: string
  label: string
  find: string
}

export const SETTINGS: SettingEntry[] = [
  { tab: 'general', label: "Projects folder", find: "Projects folder" },
  { tab: 'general', label: "Default agent", find: "Default agent" },
  { tab: 'general', label: "Terminal font size", find: "Terminal font size" },
  { tab: 'general', label: "Selecting text in a pane copies it", find: "Selecting text in a pane copies it Ctrl+C copies a highlight, Ctrl+V pastes." },
  { tab: 'general', label: "A drag always selects text", find: "A drag always selects text Off hands the drag back to the agent." },
  { tab: 'general', label: "Click moves the cursor", find: "Click moves the cursor A click puts the cursor where you clicked." },
  { tab: 'general', label: "Repair a pane's display after a resize", find: "Repair a pane's display after a resize Repaints a torn frame. Ctrl+Shift+L does it now." },
  { tab: 'general', label: "Feature notes", find: "Feature notes" },
  { tab: 'general', label: "Let the little one keep an eye on this machine", find: "Let the little one keep an eye on this machine A face on what the app does by itself." },
  { tab: 'general', label: "...and let it wander over to the pane it means, and run about now and then", find: "...and let it wander over to the pane it means, and run about now and then It walks over to the pane it is talking about." },
  { tab: 'general', label: "Which pet", find: "Which pet" },
  { tab: 'general', label: "Take what it says away after", find: "Take what it says away after" },
  { tab: 'general', label: "Show the occasional tip about what this app can do", find: "Show the occasional tip about what this app can do One card now and then, naming something hard to find." },
  { tab: 'general', label: "Ask before closing a running session", find: "Ask before closing a running session Exited panes always close without asking." },
  { tab: 'alerts', label: "Notify me when a background session goes quiet", find: "Notify me when a background session goes quiet Taskbar flash and a notification, while you are elsewhere." },
  { tab: 'alerts', label: "Chime when a session finishes its turn", find: "Chime when a session finishes its turn Plays even while you are looking at PaneForge." },
  { tab: 'alerts', label: "Send a pane's question to Telegram", find: "Send a pane's question to Telegram A waiting question reaches your phone." },
  { tab: 'alerts', label: "Say something when a pane rings its bell", find: "Say something when a pane rings its bell A CLI asking for a person marks its pane." },
  { tab: 'alerts', label: "Warn me when a running turn goes silent", find: "Warn me when a running turn goes silent" },
  { tab: 'alerts', label: "Stay out of the way while a game is running", find: "Stay out of the way while a game is running No windows and no flashing while a game runs." },
  { tab: 'alerts', label: "Do not disturb, right now", find: "Do not disturb, right now The same silence, until you turn it off." },
  { tab: 'alerts', label: "Games to watch for", find: "Games to watch for" },
  { tab: 'alerts', label: "Show what the desk is doing on Discord", find: "Show what the desk is doing on Discord Rich presence on your profile, refreshed as turns start and finish. Counts and project folder names only, never a byte of what a pane says. Needs the Discord app running; off tells Discord nothing at all." },
  { tab: 'alerts', label: "What Discord will show", find: "What Discord will show" },
  { tab: 'alerts', label: "Name the projects being worked in", find: "Name the projects being worked in The second line. Folder names of the panes whose turn is running - off leaves only the numbers, which says you are busy without saying on what." },
  { tab: 'alerts', label: "Show the elapsed clock", find: "Show the elapsed clock Discord counts up from the oldest running turn, or from when PaneForge started while everything is idle." },
  { tab: 'alerts', label: "Keep showing something while nothing is running", find: "Keep showing something while nothing is running Off clears the presence the moment the last turn finishes, so your profile only says PaneForge while there is actually work happening." },
  { tab: 'alerts', label: "First line, while a turn is running", find: "First line, while a turn is running" },
  { tab: 'alerts', label: "Second line", find: "Second line" },
  { tab: 'alerts', label: "First line, while nothing is running", find: "First line, while nothing is running" },
  { tab: 'alerts', label: "Put a clickable link under it", find: "Put a clickable link under it Discord draws the two lines above as plain text, so a URL written into them is not a link. A button is the only clickable thing a rich presence has - and Discord shows it to everyone except you, so your own profile will not have it." },
  { tab: 'alerts', label: "Button text", find: "Button text" },
  { tab: 'alerts', label: "Where it goes", find: "Where it goes" },
  { tab: 'agents', label: "Agents on this machine", find: "Agents on this machine" },
  { tab: 'agents', label: "key", find: "key" },
  { tab: 'agents', label: "Confine a third-party model to certain folders", find: "Confine a third-party model to certain folders Such a pane opens only inside the folders below." },
  { tab: 'agents', label: "Default model per agent", find: "Default model per agent" },
  { tab: 'agents', label: "Answer an agent's question for me when the answer is obvious", find: "Answer an agent's question for me when the answer is obvious Presses an answer that plainly means go on." },
  { tab: 'agents', label: "...and take the CLI's own default for the rest", find: "...and take the CLI's own default for the rest Takes the row the CLI's own arrow is on." },
  { tab: 'agents', label: "...but never while you are looking at this window", find: "...but never while you are looking at this window Nothing is pressed while you have the keyboard." },
  { tab: 'agents', label: "Wait before answering", find: "Wait before answering" },
  { tab: 'agents', label: "Dictation", find: "Dictation" },
  { tab: 'agents', label: "Transcriber", find: "Transcriber" },
  { tab: 'agents', label: "Model", find: "Model" },
  { tab: 'agents', label: "Language", find: "Language" },
  { tab: 'agents', label: "Show a mic on every pane, and enable the global push-to-talk key", find: "Show a mic on every pane, and enable the global push-to-talk key" },
  { tab: 'agents', label: "Stash", find: "Stash" },
  { tab: 'agents', label: "Keep what I copy on the Stash", find: "Keep what I copy on the Stash Everything you copy, kept. Ctrl+Shift+V reopens it." },
  { tab: 'agents', label: "Float the Stash over every other app", find: "Float the Stash over every other app A pill over every window. Ctrl+Alt+V opens it." },
  { tab: 'agents', label: "Only when I ask for it", find: "Only when I ask for it Nothing on screen until you press Ctrl+Alt+V." },
  { tab: 'agents', label: "Show itself for", find: "Show itself for" },
  { tab: 'agents', label: "Keep", find: "Keep" },
  { tab: 'agents', label: "Screenshots kept", find: "Screenshots kept" },
  { tab: 'agents', label: "Files you drop on it", find: "Files you drop on it" },
  { tab: 'agents', label: "Biggest file accepted", find: "Biggest file accepted" },
  { tab: 'agents', label: "Never remember", find: "Never remember" },
  { tab: 'system', label: "Administrator", find: "Administrator" },
  { tab: 'system', label: "Always start as administrator, with no UAC prompt", find: "Always start as administrator, with no UAC prompt One Windows approval, ever. Every pane inherits it." },
  { tab: 'system', label: "Updates", find: "Updates" },
  { tab: 'system', label: "Check for updates in the background", find: "Check for updates in the background Downloads quietly, then asks before restarting." },
  { tab: 'system', label: "Dev channel: take every build the moment it is cut", find: "Dev channel: take every build the moment it is cut Newer, sooner, less proven." },
  { tab: 'system', label: "Reopen my panes after an update restart", find: "Reopen my panes after an update restart An update feels like the app blinked." },
  { tab: 'system', label: "…and ask first, like every other restart", find: "…and ask first, like every other restart Offers the panes, as a quit or a crash does." },
  { tab: 'system', label: "After a restart or a crash", find: "After a restart or a crash" },
  { tab: 'system', label: "Transcript retention", find: "Transcript retention" },
  { tab: 'system', label: "Start PaneForge when the computer starts", find: "Start PaneForge when the computer starts Put back on every launch, not only when switched." },
  { tab: 'system', label: "Keep a PaneForge shortcut on the Desktop", find: "Keep a PaneForge shortcut on the Desktop A launch that finds it missing puts it back." },
  { tab: 'system', label: "Keep a searchable transcript of every pane", find: "Keep a searchable transcript of every pane Stored on this machine only. Deleted after days." },
  { tab: 'system', label: "Give each chat its own copy of a project", find: "Give each chat its own copy of a project The second chat on a project gets its own copy." },
  { tab: 'system', label: "Put a pane nobody has used to sleep", find: "Put a pane nobody has used to sleep Stops the agent, keeps the card and its screen." },
  { tab: 'system', label: "Sleep after (minutes)", find: "Sleep after (minutes)" },
  { tab: 'system', label: "Close a pane nobody has touched for a while", find: "Close a pane nobody has touched for a while History keeps the conversation and the screen." },
  { tab: 'system', label: "Close after (minutes)", find: "Close after (minutes)" },
  { tab: 'system', label: "Close a dev server that is serving nothing", find: "Close a dev server that is serving nothing One nothing can reach is closed after a countdown." },
  { tab: 'system', label: "Start a pane on a paired device when this machine is full", find: "Start a pane on a paired device when this machine is full Only once this machine is out of memory." },
  { tab: 'system', label: "Ask first, rather than moving it", find: "Ask first, rather than moving it You get a say before a pane starts elsewhere." },
  { tab: 'system', label: "Start new work on the other machine when the project is on GitHub", find: "Start new work on the other machine when the project is on GitHub" },
  { tab: 'system', label: "Move a finished pane to a paired device when this machine is full", find: "Move a finished pane to a paired device when this machine is full Moves an open pane, screen and conversation with it." },
  { tab: 'system', label: "Panes this machine runs itself", find: "Panes this machine runs itself" },
  { tab: 'system', label: "Projects that never leave this machine", find: "Projects that never leave this machine" },
  { tab: 'system', label: "...and move a quiet one over there even when there is still room", find: "...and move a quiet one over there even when there is still room On a clock, rather than on memory pressure." },
  { tab: 'system', label: "Right now", find: "Right now" },
  { tab: 'appearance', label: "Theme", find: "Theme" },
  { tab: 'appearance', label: "Your colour", find: "Your colour" },
  { tab: 'appearance', label: "Preview", find: "Preview" },
  { tab: 'appearance', label: "Colour in the greys", find: "Colour in the greys" },
  { tab: 'appearance', label: "How dark", find: "How dark" },
  { tab: 'appearance', label: "Sidebar glass", find: "Sidebar glass" },
  { tab: 'appearance', label: "Corners", find: "Corners" },
  { tab: 'appearance', label: "Density", find: "Density" },
  { tab: 'alerts', label: "Volume", find: "Volume" },
  { tab: 'alerts', label: "Your own sounds", find: "Your own sounds" }
]

/**
 * The settings a query hits, best first.
 *
 * Every word has to appear somewhere in the entry - AND, the same rule the tab rail uses -
 * so a second word narrows. A hit on the LABEL outranks one that only matched the
 * explaining sentence underneath: the label is what the person is looking at.
 */
export function findSettings(query: string): SettingEntry[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean)
  if (!words.length) return []
  const scored: { entry: SettingEntry; score: number }[] = []
  for (const entry of SETTINGS) {
    const label = entry.label.toLowerCase()
    const find = entry.find.toLowerCase()
    if (!words.every((w) => find.includes(w))) continue
    const inLabel = words.filter((w) => label.includes(w)).length
    scored.push({ entry, score: inLabel })
  }
  scored.sort((a, b) => b.score - a.score)
  return scored.map((s) => s.entry)
}
