/** Responses generated by xterm, rather than text entered by a person. */
export function isTerminalReply(data: string): boolean {
  return /^(?:\x1b\[(?:[IO]|[?>][\d;]*c|\??\d+;\d+R|0n|\??\d+;\d+\$y|[468];\d+;\d+t)|\x1b\](?:4;\d+|10|11|12);rgb:[^\x07\x1b]+(?:\x07|\x1b\\)|\x1bP[01]\$r[^\x1b]*\x1b\\)$/.test(data)
}

/** A saved screen can paint itself again, but must not interrogate today's PTY. */
export function withoutReplayQueries(data: string): string {
  return data.replace(
    /(?:\x1b\[|\x9b)[0-?]*[ -/]*[@-~]|(?:\x1b\]|\x9d)[^\x07\x1b\x9c]*(?:\x07|\x1b\\|\x9c)|(?:\x1bP|\x90)[^\x1b\x9c]*(?:\x1b\\|\x9c)|\x1bZ/g,
    (original) => {
      const sequence = original.replace(/^\x9b/, '\x1b[').replace(/^\x9d/, '\x1b]')
        .replace(/^\x90/, '\x1bP').replace(/\x9c$/, '\x1b\\')
      if (sequence === '\x1bZ') return ''
      if (/^\x1b\[(?:[0-?]*[cn]|[0-?]*\$p|(?:14|16|18|19|20|21)(?:;\d*)*t)$/.test(sequence)) return ''
      if (/^\x1b\](?:4|10|11|12);/.test(sequence) && sequence.includes('?')) return ''
      if (sequence.startsWith('\x1bP$q')) return ''
      return original
    }
  )
}
