import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { ReviewStore } from '../server/review-store.mjs';

const session={id:'session_1',nativeSessionId:'native_1',title:'A <title>',provider:'codex',cwd:process.cwd(),items:[]};
test('reviews survive restart and decision or blocked acknowledgement never clears attention',()=>{const dir=mkdtempSync(join(tmpdir(),'pf-reviews-'));try{const store=new ReviewStore(dir);store.record({id:'decision_1',sessionId:session.id,kind:'decision',proof:'claimed',report:'Need approval',prompt:'Original'},session);store.record({id:'blocked_1',sessionId:session.id,kind:'blocked',proof:'measured',report:'Blocked',prompt:'Original'},session);assert.deepEqual(store.ack('decision_1',true),{ok:true,clearedAttention:false});assert.deepEqual(store.ack('blocked_1',false),{ok:true,clearedAttention:false});const reloaded=new ReviewStore(dir);assert.equal(reloaded.list().length,2);assert.equal(reloaded.list().every(r=>r.attention),true);}finally{rmSync(dir,{recursive:true,force:true});}});
test('completed turn stores exact request and its matching final outcome once',()=>{const dir=mkdtempSync(join(tmpdir(),'pf-reviews-'));try{const store=new ReviewStore(dir);const active={...session,items:[{id:'old',turnId:'oldturn',type:'agentMessage',text:'old output'},{id:'new',turnId:'turn_1',type:'agentMessage',text:'final output'}],activeReviewRequest:{requestId:'request_1',text:'original request'}};const record=store.captureCompletedTurn(active,{id:'turn_1',status:'completed'});assert.match(record.report,/final output/);assert.doesNotMatch(record.report,/old output/);assert.equal(record.prompt,'original request');assert.equal(store.captureCompletedTurn(active,{id:'turn_1',status:'completed'}),null);const html=readFileSync(record.reportPath,'utf8');assert.match(html,/A &lt;title&gt;/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('only a retained completed outcome is informational',()=>{const dir=mkdtempSync(join(tmpdir(),'pf-reviews-'));try{const store=new ReviewStore(dir);const completed={...session,items:[{id:'new',turnId:'turn_2',type:'agentMessage',text:'done'}],activeReviewRequest:{requestId:'request_2',text:'original request'}};assert.equal(store.captureCompletedTurn(completed,{id:'turn_2',status:'completed'}).informational,true);const missing={...session,items:[],activeReviewRequest:{requestId:'request_3',text:'original request'}};assert.equal(store.captureCompletedTurn(missing,{id:'turn_3',status:'completed'}).informational,false);}finally{rmSync(dir,{recursive:true,force:true});}});
test('review records require a real native session identity',()=>{const dir=mkdtempSync(join(tmpdir(),'pf-reviews-'));try{assert.throws(()=>new ReviewStore(dir).record({id:'result_1',sessionId:'session_1',kind:'result',proof:'claimed',report:'output'}, {...session,nativeSessionId:null}),/native session ID/);}finally{rmSync(dir,{recursive:true,force:true});}});

test('completed capture persists request identity and observed lane',()=>{const dir=mkdtempSync(join(tmpdir(),'pf-reviews-'));try{const store=new ReviewStore(dir);
 const s={id:'session-request',nativeSessionId:'native-request',title:'Lane work',provider:'codex',cwd:'/tmp/lane',laneId:'lane-b',laneName:'Lane B',kind:'conversation',activeReviewRequest:{requestId:'request-identity',text:'Please implement it'},items:[{id:'answer',type:'agentMessage',turnId:'turn-request',text:'Completed.'}]};
 const record=store.captureCompletedTurn(s,{id:'turn-request',status:'completed'});
 assert.equal(record.requestId,'request-identity');assert.equal(record.lane,'Lane B · lane-b');assert.equal(s.activeReviewRequest,undefined);
}finally{rmSync(dir,{recursive:true,force:true});}});
