// What the Stash refuses to remember.
//
// The bug this pins is the one that never shows up on screen: a password copied out of a
// password manager landing in `history.json` as plaintext and sitting there for 200
// items. There is nothing to look at either way - a working exclusion and a broken one
// draw exactly the same empty row - so the only proof is this file.
//
// It also pins the direction of the two uncertain calls, because both are the kind that
// get "simplified" later by somebody who has not read why:
//   - a Windows format whose DWORD we cannot see is treated as a NO;
//   - the built-in list is markers only, never secret SHAPES, because copying an API key
//     to paste it at an agent is an everyday move in this app.
//
//   node scripts/conceal-test.mjs

import { buildSync } from 'esbuild'
import { strict as assert } from 'node:assert'
import { mkdirSync, rmSync } from 'node:fs'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const work = join(tmpdir(), 'pf-conceal-test')
rmSync(work, { recursive: true, force: true })
mkdirSync(work, { recursive: true })

const out = join(work, 'conceal.bundle.cjs')
buildSync({
  absWorkingDir: root,
  entryPoints: ['src/shared/conceal.ts'],
  bundle: true,
  format: 'cjs',
  platform: 'node',
  outfile: out
})
const { CONCEALED_FORMATS, compileDeny, concealedBy, deniedBy } = createRequire(import.meta.url)(
  out
)

let checks = 0
const is = (actual, expected, what) => {
  assert.equal(actual, expected, what)
  checks++
}
const ok = (cond, what) => {
  assert.ok(cond, what)
  checks++
}

// ---------------------------------------------------------------------------
// The marker: the copying app said no

is(concealedBy(['public.utf8-plain-text']), null, 'an ordinary text copy is remembered')
is(concealedBy([]), null, 'an empty clipboard conceals nothing')
is(
  concealedBy(['public.utf8-plain-text', 'org.nspasteboard.ConcealedType']),
  'org.nspasteboard.ConcealedType',
  '1Password/Bitwarden/KeePassXC on macOS: the clip is a password'
)
is(
  concealedBy(['org.nspasteboard.TransientType', 'public.utf8-plain-text']),
  'org.nspasteboard.TransientType',
  'transient means it was not typed by a person and is not worth a history slot'
)
is(
  concealedBy(['org.nspasteboard.AutoGeneratedType']),
  'org.nspasteboard.AutoGeneratedType',
  'auto-generated, same answer'
)
is(
  concealedBy(['CF_UNICODETEXT', 'ExcludeClipboardContentFromMonitorProcessing']),
  'ExcludeClipboardContentFromMonitorProcessing',
  'the strong Windows format: no other process should even look'
)
is(
  concealedBy(['CF_UNICODETEXT', 'CanIncludeInClipboardHistory']),
  'CanIncludeInClipboardHistory',
  'presence is a NO: allowing is the default and needs no format at all, so registering it can only mean no'
)
is(
  concealedBy(['CanUploadToCloudClipboard']),
  'CanUploadToCloudClipboard',
  'and the cloud-clipboard opt-out reads the same way'
)

// Which marker fired is returned, not just "true" - this is a path whose output nobody
// can ever see by definition, so the one line the log gets has to name the convention.
ok(
  CONCEALED_FORMATS.includes(concealedBy(['org.nspasteboard.ConcealedType'])),
  'the answer is the marker itself, so a log line can name it'
)

// macOS hands back an opaque `dyn.` wrapper for a type an app never declared a UTI for.
is(
  concealedBy(['dyn.ah62d4rv4gu8zg2pxsvw0e55bsmwca7d3sBZa.org.nspasteboard.ConcealedType']),
  'org.nspasteboard.ConcealedType',
  'a dyn-wrapped marker still counts'
)
is(
  concealedBy(['ORG.NSPASTEBOARD.CONCEALEDTYPE']),
  'org.nspasteboard.ConcealedType',
  'and case is not load-bearing'
)

// The built-in list is markers ONLY. If somebody ever adds a secret shape to it, this
// fails - copying an API key to paste it at an agent has to keep working.
is(
  concealedBy(['public.utf8-plain-text']),
  null,
  'no built-in guess about content: sk-ant-... is a normal clip until the user says otherwise'
)

// ---------------------------------------------------------------------------
// The deny list: the user's own guess

is(compileDeny('').length, 0, 'empty by default, so nothing is swallowed unasked')
is(compileDeny('   \n\n  ').length, 0, 'blank lines are not rules')
is(compileDeny('# a comment\nstaging').length, 1, 'a # line is a comment')

const subs = compileDeny('staging')
is(deniedBy('deploy to STAGING now', subs), subs[0].source, 'a plain line is a substring, any case')
is(deniedBy('production', subs), null, 'and it does not match everything else')

const re = compileDeny('/^ghp_[A-Za-z0-9]{20,}$/')
ok(deniedBy('ghp_' + 'a'.repeat(36), re), '/regex/ is compiled as one')
is(deniedBy('a ghp_ mention in prose', re), null, 'anchors in the rule are honoured')

// A `g` flag carries lastIndex between clips, so the same rule would match every OTHER
// copy. That is the sort of bug nobody reports because the feature only half works.
const g = compileDeny('/secret/g')
ok(deniedBy('secret one', g), 'a global rule matches the first clip')
ok(deniedBy('secret two', g), 'and the next one too - lastIndex is not carried')

const mixed = compileDeny('bad(\nfine')
is(mixed.length, 2, 'a line that is not a valid regex is still a valid substring')
ok(deniedBy('x bad( y', mixed), 'and it matches literally, brackets and all')

const broken = compileDeny('/[unclosed/\nkeepme')
is(broken.length, 1, 'an unparseable /regex/ is one dead rule, never a dead list')
ok(deniedBy('keepme', broken), 'the rules after it still work')

is(deniedBy('anything at all', compileDeny('')), null, 'an empty list denies nothing')

rmSync(work, { recursive: true, force: true })
console.log(`PASS conceal: ${checks} assertions`)
